### PR TITLE
fix(cards): incorrectly formatting decimal values

### LINKED ISSUE #1129: [TimeSeriesCard] Decimal Separator incorrect in tooltip in non-English languages
[Internal Watson-IoT/pal-tracking#396](https://github.ibm.com/Watson-IoT/pal-tracking/issues/396)

### Describe the bug
In European locales decimals should be formatted with commas
image

### To Reproduce

Go to the local specific story and look at a tooltip:
https://carbon-addons-iot-react.com/?path=/story/watson-iot-timeseriescard--locale

### PR DESCRIPTION
**Pull request by scottdickerson**
Closes #1129

**Summary**

- Our cards were formatting numbers for display without taking the locale into account

**Change List (commits, features, bugs, etc)**

- fix(TimeSeriesCard): pass locale along when formatting numbers
- fix(TableCard): pass locale along with formatting numbers for precision
- fix(ValueCard): pass locale along when formatting numbers for precision
- refactor(cardUtilityFunctions): centralize all formatting functions into one place
- test(icudata): to run testcases in Node need to add ICU support for locale formatting

**Acceptance Test (how to verify the PR)**

- Verify the ValueCard, TableCard and TimeSeriesCard stories haven't changed in the diff except where they should explicitly change

### CODE REVIEW

File: src/utils/cardUtilityFunctions.js [hunk 1]
```diff
@@ -123,6 +123,31 @@ export const getUpdatedCardSize = oldSize => {
   return newSize;
 };
 
+export const formatNumberWithPrecision = (value, precision, locale) =>
```
Comment (tay1orjones) [inline src/utils/cardUtilityFunctions.js:126]: A jsdoc style comment would be beneficial here

```
/**
 * Find variables that match a given value
 * @param {number} value - The description of the value
 * @param {number} precision - The description of the precision
 * @param {string} locale - The description of the locale
 * @return {string} The value formatted with the precision specified
 */
```

**Comment by scottdickerson** [comment]
@tay1orjones resubmitted with better jsdocs, thanks!
