### PR TITLE
fix(tablecard): added explicit check for 0

### LINKED ISSUE #1015: [TableCard] Exporting table to CSV exports 0 as blank
### Describe the bug

When viewing a table with data in it including 0 and you decide to export this to a CSV file, it exports the fields with 0 as a blank. There are actually fields that are blank but a 0 is a valid value. Importing the CSV into a spreadsheet shows the fields as blank/missing data and not a 0.

### To Reproduce

1. Open a tablecard with 0's as cell values
2. Click export
3. Examine the CSV or spreadsheet and all 0 fields will be blank

### Expected behavior

0's should display in CSV

### Environment/versions:

- OS: [MacOS]
- Browser: [firefox]
- `carbon-addons-iot-react` version: latest

### Additional context

Screen Shot 2020-03-18 at 12 17 55 PM

Screen Shot 2020-03-18 at 12 18 09 PM

Internal issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/861

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific deadline

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #1015 

**Summary**

- The integer 0 was being treated as falsy, which caused the 0 to be omitted. This PR adds an explicit check for `=== 0`

**Change List (commits, features, bugs, etc)**

- Added 0 values to mock table data for future testing
- Added explicit check for integer 0 in CSV utility function
- Added test for use-case
- Added more comments about the utility functions
- Updated old test to reflect new 0 value
- Updated snapshots

**Acceptance Test (how to verify the PR)**

1. Go to `/?path=/story/watson-iot-tablecard--size-large` and download the CSV
2. See that the 0 values appear in the pressure column

Old:
Screen Shot 2020-03-18 at 12 18 09 PM

Updated:
Screen Shot 2020-03-18 at 1 33 37 PM

### CODE REVIEW

File: src/utils/componentUtilityFunctions.js [hunk 1]
```diff
@@ -18,26 +18,56 @@ import {
...
+  csv += `${columnHeaders.join(',')}\n`;
   data.forEach(item => {
-    object.forEach(arrayHeader => {
-      csv += `${item.values[arrayHeader] ? item.values[arrayHeader] : ''},`;
+    columnHeaders.forEach(arrayHeader => {
+      // if item is of arrayHeader, add value
+      // else if, check if the value is integer 0 as 0 is treated as false.
+      // Swap the 0 for a string literal 0 so that it displays in the csv
+      // else, return empty string
+      if (item.values[arrayHeader]) {
```
Comment (scottdickerson) [inline src/utils/componentUtilityFunctions.js]: can we instead just do a isNil check on this value in the ternary?

Comment (sstone2423) [reply src/utils/componentUtilityFunctions.js]: Fixed
