### PR TITLE
fix(button): loading maintains same height in button

### LINKED ISSUE #709: [Button] Loading state doesn't maintain height from "size" prop
### Describe the bug

When `<Button>` is in loading state, the size of the button increases due to spinner padding.  We should ensure (and add stories to verify) that loading maintains whatever size was passed

### To Reproduce

View the `loading` story for Button
View the `not loading` story for Button
Notice the sizes are different

### Expected behavior

loading state should respect height guidelines from size prop.

### Environment/versions:

any

### Additional context

image

### Specific timeline issues / requests

soon would be good

### PR DESCRIPTION
**Pull request by jessieyan**
Make sure loading spinner within the height inside a button

Closes #709

### CODE REVIEW

**Comment by jessieyan** [comment]
This is to resolve Issue #709.

File: src/components/Button/Button.jsx [hunk 1]
```diff
@@ -7,7 +7,10 @@ import styled from 'styled-components';
 const StyledButton = styled(CarbonButton)`
   &&& {
     justify-content: flex-start;
-
+    .bx--loading {
```
Comment (tay1orjones) [inline src/components/Button/Button.jsx]: If the consumer of this component has configured their codebase to use a different prefix than the default `bx`, these styles will not apply. Instead of the hardcoded `.bx`, we can replace it with the prefix variable:

```
import {settings} from carbon-components;

const {prefix} = settings;


... then in the style declaration

.${prefix}--loading {

}
```

Comment (jessieyan) [reply src/components/Button/Button.jsx]: Done. Thanks!
