### PR TITLE
fix(dashboardgrid): 6277-Dashboard-Grid-Tile-Jump

### LINKED ISSUE #780: [DashboardGrid] isEditable causes tiles to jump on initial render
<sub>[Internal tracking issue #134](https://github.ibm.com/Watson-IoT/pal-tracking/issues/134)</sub>

### Describe the bug

On initial render, the tiles jump/move. They should be static from initial render.

resize rendering

### To Reproduce

1. [View the story in the storybook](https://carbon-addons-iot-react.com/?path=/story/watson-iot-dashboard-grid--dashboard-is-edtiable)
1. Flip between the different dashboard grid stories, you'll see the reflow only on the `isEditable` story

### Expected behavior

The cards are static on initial render, no moving. They move/flow only when the browser is resized to effect the layout of the cards.

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: `v2.18.0`

### PR DESCRIPTION
**Pull request by psdixit**
Closes #780 

**Summary**

Dashboard Grid (dashboard,isEditable) : Tiles on dashboard grid is jump (animated) while rending the page.

**Change List (commits, features, bugs, etc)**

src/components/Dashboard/DashboardGrid.jsx
src/components/Dashboard/snapshots/DashboardGrid.story.storyshot

**Acceptance Test (how to verify the PR)**

Click on Dashboard (dashboard,isEditable) link, Dashboard tiles should be rendering static without animation

### CODE REVIEW

**Comment by psdixit** [comment]
Hi @davidicus @stuckless 

Please review the PR #894 related the defect #780 .


Thanks,
P S Dixit

**Comment by tay1orjones** [comment]
Is this a duplicate of #803? They both have the same graphite issue number.

File: src/components/Dashboard/DashboardGrid.jsx [hunk 1]
```diff
@@ -162,6 +162,13 @@ const DashboardGrid = ({
     [childrenArray]
   );
 
+  const [animationState, setAnimationState] = useState(false);
+  useEffect(() => {
+    setTimeout(() => {
```
Comment (tay1orjones) [inline src/components/Dashboard/DashboardGrid.jsx]: Is the timeout necessary here? useEffect is ran after the first render and after every update.

Comment (psdixit) [reply src/components/Dashboard/DashboardGrid.jsx]: > Is the timeout necessary here? useEffect is ran after the first render and after every update.

Hi @tay1orjones ,

The element animation depends on the property "shouldAnimate". It is initially set to false and animation should not be effect the element.
I'll change the value of "shouldAnimate" property to true and it should animate,
But it doesn’t as all of this happens really fast with setState , and browser decides to render changes on the end of result, 
That's why i used the settimeout, this way we can achive this animation effect.

Comment (tay1orjones) [reply src/components/Dashboard/DashboardGrid.jsx]: Yes, the timeout works because it prevents the batching of setState component updates. A better way to achieve this will be to use `requestAnimationFrame` instead of `setTimeout`.

Additionally, with this as-is, we have lost configurability of the animation via the `isEditable` prop.

I will push an update to this branch to make clear these two suggestions.
