### PR TITLE
fix(timeseries): set the right amout of chart labels

### LINKED ISSUE #984: [BarChartCard] Bars going beyond border
### Describe the bug

BarchartCard as seen in [this](https://deploy-preview-961--carbon-addons-iot-react.netlify.com/?path=/story/watson-iot-dashboard--full-screen-bar-chart-card) dashboard storybook

image

### To Reproduce

1. Go to '[this](https://deploy-preview-961--carbon-addons-iot-react.netlify.com/?path=/story/watson-iot-dashboard--full-screen-bar-chart-card) story
2. See error

### Environment/versions:

- OS: MacOS
- Browser: Chrome

Pal tracking [issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/298)

### PR DESCRIPTION
**Pull request by enricoberti**
Closes #984 

**Summary**

It's very likely related to a bug on carbon-charts I just reported: https://github.com/carbon-design-system/carbon-charts/issues/521

**Acceptance Test (how to verify the PR)**

- ?path=/story/watson-iot-dashboard--full-screen-bar-chart-card should render correctly

### CODE REVIEW

File: src/components/TimeSeriesCard/TimeSeriesCard.jsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ import filter from 'lodash/filter';
 import memoize from 'lodash/memoize';
 import capitalize from 'lodash/capitalize';
 import useDeepCompareEffect from 'use-deep-compare-effect';
+import uniqBy from 'lodash/uniqBy';
```
Comment (sstone2423) [inline src/components/TimeSeriesCard/TimeSeriesCard.jsx]: FYI, I believe this can by done by Sets now 👍 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

Comment (enricoberti) [reply src/components/TimeSeriesCard/TimeSeriesCard.jsx]: again, force of habit, thanks!

**Comment by enricoberti** [comment]
@bjornalm @sstone2423 pushed the lodash dependency removal. There's a problem with unit testing though: to check for the effectiveness of this bug fix we would need to compare the dimensions of two svg elements with getBoundingClientRect() and compare the heights. getBoundingClientRect() is not implemented in enzyme/jsdom so it would be a bit useless to mock it... Eventually I want to help out the Carbon Charts project to fix this (already found where it bugs) so can we merge without tests?
