### PR TITLE
[HierarchyList] Test coverage, conditional rendering, and defaultSelected expansion

### LINKED ISSUE #892: [HierarchyList] If I start the list with a child element selected, the parent is collapsed
### Describe the bug

Create the hierarchy list with defaultSelectedId.  The parent is not expanded by default and if the element is offscreen in a scroll pane, it's not visible.  We should probably scroll it into view if it's offscreen (even if it's in it's own pane)

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #892 

**Summary**

- Coverage was failing as it was under 80%
- The `secondaryValue` div was still being rendered, even when it was null
- The `defaultSelectId`'s parent elements are now expanded by default
- List scrolls to the `defaultSelectedId`

**Change List (commits, features, bugs, etc)**

- Additional tests added to rise to >80%
- Conditional rendering added to `ListItem`. If `secondaryValue` is null, it will not render, freeing up the other 50% of the width
- Additional functions for recursively searching were added to find items by `id`
- New story added to show `defaultSelectedId` behavior
- `toBeTruthy()` functions renamed to `toBeInTheDocument()` where applicable to give a better idea of what I am actually testing for
- Ref added to `defaultSelectedId`'s DOM element
  - Custom hook magic to determine if the node is set before trying to scroll

**Acceptance Test (how to verify the PR)**

- See the 'with defaultSelectedId' HierarchyList story and see that an item is pre-selected, its parent is expanded, and the element is scrolled into view

### CODE REVIEW

File: src/components/List/HierarchyList/HierarchyList.jsx [hunk 1]
```diff
@@ -87,25 +87,98 @@ export const searchItem = (item, searchTerm) => {
...
+
+/**
+ * The ref should only be set if the item is selected by default. By using a callback,
+ * we can check if a node is properly attached to the ref, then scroll to it within the list
+ */
+const useHookWithRefCallback = () => {
+  const ref = useRef(null);
+  const setRef = useCallback(
+    node => {
+      if (node) {
```
Comment (scottdickerson) [inline src/components/List/HierarchyList/HierarchyList.jsx]: So functionally this is really scrollIntoViewAndSetRef?

Comment (scottdickerson) [reply src/components/List/HierarchyList/HierarchyList.jsx]: do you really need the ref at all at this point?

File: src/components/List/HierarchyList/HierarchyList.jsx [hunk 2]
```diff
@@ -87,25 +87,98 @@ export const searchItem = (item, searchTerm) => {
...
+/**
+ * Searches an item for a specific id
+ * @param {Object} item to be searched
+ * @param {string} searchId
+ * @returns {Boolean} found or not
+ */
+export const searchForItemId = (item, searchId) => {
+  if (
+    // Check if the value or secondary value has a match
+    item.id.toLowerCase().search(searchId.toLowerCase()) !== -1
```
Comment (scottdickerson) [inline src/components/List/HierarchyList/HierarchyList.jsx]: Can't this function and searchForItemValue be refactored into one to take a list of content keys to search for so the same codebase can be shared?

File: src/components/List/HierarchyList/HierarchyList.jsx [hunk 3]
```diff
@@ -87,25 +87,98 @@ export const searchItem = (item, searchTerm) => {
...
+    node => {
+      if (node) {
+        // Check if a node is actually passed. Otherwise node would be null.
+        // node is the text of the item
+        // parentNode is the container div with the button role
+        // parentNode.parentNode is the list content, which is also the element to be scrolled
+        // the offsetHeight needs to be multiplied by 3 to be able to view the whole element
+        const offset =
+          node.offsetTop -
+          node.parentNode.offsetHeight -
```
Comment (scottdickerson) [inline src/components/List/HierarchyList/HierarchyList.jsx]: need to optionally null check these keys

File: src/components/List/HierarchyList/HierarchyList.jsx (hunk 1 above)
Comment (sstone2423) [reply src/components/List/HierarchyList/HierarchyList.jsx]: I renamed the function to a more suited name.

The ref is still needed as its the pointer to the DOM node that needs to be scrolled to

File: src/components/List/HierarchyList/HierarchyList.jsx (hunk 3 above)
Comment (sstone2423) [reply src/components/List/HierarchyList/HierarchyList.jsx]: Fixed

File: src/components/List/HierarchyList/HierarchyList.jsx (hunk 2 above)
Comment (sstone2423) [reply src/components/List/HierarchyList/HierarchyList.jsx]: Refactored and made a general util search function
